version: '3.7'

services:
  instruments:
    build: .  
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: 
      - .envdb
  db:
    image: mysql:5.7
    volumes: 
      - ./sql:/docker-entrypoint-initdb.d
    env_file: 
      - .envdb